Update GitHub actions in build_check_links.yml workflow
Fixes the following error that occurs with the latest ubuntu-latest
(now ubuntu-24.04, was probably ubuntu-22.04 or even ubuntu-20.04):

Installing Bundler
  /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/gem install bundler -v ~> 2 --no-document
  ERROR:  Error installing bundler:
        The last version of bundler (~> 2) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
        bundler requires Ruby version >= 3.1.0. The current ruby version is 2.6.7.197.
  Took  14.29 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.6.7/x64/bin/gem' failed with exit code 1